#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/
schemas:
  - halLink: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "a Hypertext Application Language link",
        "properties": {
          "name":  { "type": "string" },
          "href":  { "type": "string" },
          "tempted": {"type": "string"} }
        },
        "required": [ "href" ]
      }
/register:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          mobilePhone: string
          email: string
          password: string
    responses:
      200:
        body:
          application/json:
            properties:
              user: halLink
              userInfo: halLink
/user:
  get:
    queryParameters:
      field: string
      value: string
    responses:
      200:
        body:
          application/json:
            properties:
              user: halLink
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                id: integer
                email: string
                mobilePhone: string
                password: string

/userInfo/{id}:
  get:
  put:
/logic-puzzle/{id}:
  description: A logic exam subject
  get:
/userSubjects:
  get:
    queryParameters:
      userId:
    responses:
      200:
        body:
          application/json:
            properties:
              subjects: halLink[]
