#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/
mediaType: application/json
types:
  CommonResp:
    description: standard Response For All Request
    type: object
    properties:
      status: number
      [data]: object
      message: string
    example:
      {
        "status": 200,
        "data": {
          "name": "tom",
          "email": "tom@gmail.com"
        },
        "message": ""
      }
  Item:
    type: object
    properties:
      initBox: number[]
      flowChartImgUrl: string
      instruction: string[]
  Phone:
    pattern: ^\d{11}$
  RegistrationInfo:
    type: object
    properties:
      useremail: string
      phoneNumber: Phone
      password: string
/registration:
  post:
    body:
      type: RegistrationInfo
    description: Create a new user
    responses:
      200:
        body:
          application/json:
            type: CommonResp
/item/{id}:
  uriParameters:
    id:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            type: Item
/score:
/user-items:
