#%RAML 1.0
title: TWARecurting API
description:
version: V1
baseUri: http://api.bronzesword.com/
schemas:
  - halLink: |
      { "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "a Hypertext Application Language link",
        "properties": {
          "name":  { "type": "string" },
          "href":  { "type": "string" },
          "tempated": { "type": "boolean" }
        },
        "required": [ "href" ]
      }
/register:
  post:
    responses:
      200:
        body:
          application/json:
            properties:
              id: integer
              user: halLink
/user/{id}:
  get:
/userInfo/{id}:
  get:
  put:
/subject/{id}:
  description: A logic exam subject
  get:
/userSubjects:
  get:
    queryParameters:
      userId:
    responses:
      200:
        body:
          application/json:
            properties:
              subjects: halLink[]
